[package]
name = "spotifycli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspotify = { version = "0.11.2", features = ["cli"] }
tokio = { version = "1.12.0", features = ["full"] }